package com.chris.rosiehome;

import android.animation.*; import android.app.*; import android.appwidget.*; import android.content.*; import android.graphics.*; import android.graphics.drawable.*; import android.os.*; import android.view.*; import android.view.animation.*; import android.widget.*; import java.text.*; import java.util.*;

/** Modern, frame-synchronised recreation informed by the recovered Rosie marker/depth controls. */
public final class RosieView extends ViewGroup {
 private final LauncherActivity activity; private final ArrayList<AppEntry> apps; private final ArrayList<AppEntry> favorites=new ArrayList<>();
 private final Paint paint=new Paint(3); private final GestureDetector gestures; private final android.content.SharedPreferences prefs;
 private int page=3, pages=7, columns=4, rows=4; private float iconDp=60, density, drag, downX; private boolean drawer, overview, editing; private ValueAnimator settle; private AppWidgetHostView widget;
 private final RectF clock=new RectF(), dock=new RectF(); private final PolynomialEase ease=new PolynomialEase();
 RosieView(LauncherActivity a){super(a);activity=a; density=getResources().getDisplayMetrics().density; setWillNotDraw(false); setLayerType(LAYER_TYPE_HARDWARE,null);
  prefs=a.getSharedPreferences("layout",0); page=prefs.getInt("page",3); columns=prefs.getInt("columns",4); iconDp=prefs.getInt("icons",60);
  apps=new ArrayList<>(a.apps()); loadFavorites(); setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{0xff132536,0xff35505b,0xff090f17}));
  gestures=new GestureDetector(a,new GestureDetector.SimpleOnGestureListener(){ public boolean onDown(android.view.MotionEvent e){downX=e.getX(); if(settle!=null)settle.cancel();return true;}
   public boolean onSingleTapUp(android.view.MotionEvent e){return tap(e.getX(),e.getY());}
   public void onLongPress(android.view.MotionEvent e){ if(!drawer){editing=true;performHapticFeedback(HapticFeedbackConstants.LONG_PRESS);invalidate();} }
   public boolean onFling(android.view.MotionEvent e1,android.view.MotionEvent e2,float vx,float vy){ if(drawer)return false; finishDrag(vx);return true;}
  });
 }
 private void loadFavorites(){ String saved=prefs.getString("favorites",""); for(String s:saved.split(";"))for(AppEntry a:apps)if(a.component.flattenToString().equals(s))favorites.add(a); if(favorites.isEmpty())for(int i=0;i<Math.min(112,apps.size());i++)favorites.add(apps.get(i)); }
 @Override protected void onMeasure(int w,int h){int W=MeasureSpec.getSize(w),H=MeasureSpec.getSize(h);setMeasuredDimension(W,H);for(int i=0;i<getChildCount();i++)getChildAt(i).measure(MeasureSpec.makeMeasureSpec(W-columns*8,MeasureSpec.EXACTLY),MeasureSpec.makeMeasureSpec(H/3,MeasureSpec.EXACTLY));}
 @Override protected void onLayout(boolean c,int l,int t,int r,int b){for(int i=0;i<getChildCount();i++)getChildAt(i).layout(columns*4,b/2-columns*4,r-columns*4,b/2+b/3-columns*4);}
 @Override protected void onDraw(Canvas c){super.onDraw(c); float W=getWidth(),H=getHeight(),top=getPaddingTop()+dp(30); dock.set(0,H-dp(112),W,H);
  if(drawer){drawDrawer(c,W,H);return;} if(overview){drawOverview(c,W,H);return;}
  drawClock(c,W,top); c.save(); float progress=drag/W; float sink=(float)Math.sin(Math.PI*Math.min(1,Math.abs(progress))); c.translate(drag,dp(25)*sink); float scale=1-.16f*sink;c.scale(scale,scale,W/2,H/2); drawWorkspace(c,W,H);c.restore(); drawIndicators(c,W,H);drawDock(c,W,H);
  if(editing)drawEdit(c,W,H);
 }
 private void drawClock(Canvas c,float W,float top){clock.set(dp(18),top,W-dp(18),top+dp(180));paint.setColor(0x77000000);c.drawRoundRect(clock,dp(18),dp(18),paint);float split=clock.left+clock.width()*.58f;paint.setColor(0xff111111);c.drawRoundRect(new RectF(clock.left+dp(14),clock.top+dp(15),split-dp(3),clock.bottom-dp(42)),dp(9),dp(9),paint);c.drawRoundRect(new RectF(split+dp(3),clock.top+dp(15),clock.right-dp(14),clock.bottom-dp(42)),dp(9),dp(9),paint);
  String time=new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date()); text(c,time,(clock.left+split)/2,clock.top+dp(90),dp(51),Color.WHITE,true);drawPartlyCloudy(c,(split+clock.right)/2,clock.top+dp(69));text(c,"PARTLY CLOUDY",(split+clock.right)/2,clock.bottom-dp(51),dp(10),0xfff2f2f2,true);text(c,new SimpleDateFormat("EEEE, MMMM d",Locale.getDefault()).format(new Date()),clock.centerX(),clock.bottom-dp(13),dp(15),0xffeeeeee,true);text(c,"Static weather display",clock.centerX(),clock.bottom+dp(19),dp(12),0xffc8d6dc,true);postInvalidateOnAnimation();
 }
 private void drawPartlyCloudy(Canvas c,float x,float y){float phase=(SystemClock.uptimeMillis()%6000L)/6000f,drift=(float)Math.sin(phase*Math.PI*2)*dp(4);c.save();c.rotate(phase*360,x-dp(18),y-dp(18));paint.setColor(0xffffc33b);c.drawCircle(x-dp(18),y-dp(18),dp(20),paint);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(dp(3));for(int i=0;i<8;i++){double a=i*Math.PI/4;c.drawLine(x-dp(18)+(float)Math.cos(a)*dp(25),y-dp(18)+(float)Math.sin(a)*dp(25),x-dp(18)+(float)Math.cos(a)*dp(32),y-dp(18)+(float)Math.sin(a)*dp(32),paint);}paint.setStyle(Paint.Style.FILL);c.restore();x+=drift;paint.setColor(0xffe7edf0);c.drawCircle(x-dp(18),y+dp(10),dp(20),paint);c.drawCircle(x+dp(5),y,dp(27),paint);c.drawCircle(x+dp(30),y+dp(12),dp(18),paint);c.drawRoundRect(new RectF(x-dp(38),y+dp(9),x+dp(49),y+dp(31)),dp(11),dp(11),paint);}
 private void drawWorkspace(Canvas c,float W,float H){float start=clock.bottom+dp(45),cellW=W/columns,cellH=(H-dp(125)-start)/rows;int base=page*columns*rows;for(int i=0;i<columns*rows;i++){int n=base+i;if(n>=favorites.size())break;drawApp(c,favorites.get(n),(i%columns+.5f)*cellW,start+(i/columns+.46f)*cellH,iconDp);} }
 private void drawApp(Canvas c,AppEntry a,float x,float y,float size){Drawable d=a.icon;int s=(int)dp(size);d.setBounds((int)x-s/2,(int)y-s/2,(int)x+s/2,(int)y+s/2);d.draw(c); text(c,a.label,x,y+s/2+dp(18),dp(13),Color.WHITE,true);}
 private void drawIndicators(Canvas c,float W,float H){float y=H-dp(125);for(int i=0;i<pages;i++){paint.setColor(i==page?0xffffffff:0x66888888);c.drawCircle(W/2+(i-3)*dp(12),y,i==page?dp(3.5f):dp(2.5f),paint);}}
 private void drawDock(Canvas c,float W,float H){paint.setShader(new LinearGradient(0,dock.top,0,H,new int[]{0xbb777777,0xee171717,0xff050505},null,Shader.TileMode.CLAMP));c.drawPath(dockPath(W,H),paint);paint.setShader(null);text(c,"☎",W*.18f,H-dp(43),dp(35),Color.WHITE,true);paint.setColor(0xff202020);c.drawCircle(W/2,H-dp(48),dp(42),paint);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(dp(2));paint.setColor(0xff999999);c.drawCircle(W/2,H-dp(48),dp(40),paint);paint.setStyle(Paint.Style.FILL); for(int r=0;r<4;r++)for(int q=0;q<4;q++){paint.setColor(0xffeeeeee);c.drawRect(W/2-dp(15)+q*dp(9),H-dp(63)+r*dp(9),W/2-dp(9)+q*dp(9),H-dp(57)+r*dp(9),paint);}text(c,"＋",W*.82f,H-dp(43),dp(38),Color.WHITE,true);}
 private Path dockPath(float W,float H){Path p=new Path();p.moveTo(0,H);p.lineTo(0,H-dp(62));p.quadTo(W*.20f,H-dp(104),W*.37f,H-dp(89));p.quadTo(W/2,H-dp(122),W*.63f,H-dp(89));p.quadTo(W*.8f,H-dp(104),W,H-dp(62));p.lineTo(W,H);p.close();return p;}
 private void drawDrawer(Canvas c,float W,float H){paint.setColor(0xf2101214);c.drawRect(0,0,W,H,paint);text(c,"All apps",dp(24),dp(64),dp(26),Color.WHITE,false);text(c,"×",W-dp(32),dp(64),dp(34),Color.WHITE,true);int cols=4;float cw=W/cols,start=dp(120),ch=dp(112);for(int i=0;i<apps.size();i++){float y=start+(i/cols)*ch;if(y>H+dp(80))break;drawApp(c,apps.get(i),(i%cols+.5f)*cw,y,56);}}
 private void drawOverview(Canvas c,float W,float H){paint.setColor(0xdd080b0e);c.drawRect(0,0,W,H,paint);text(c,"Leap view",W/2,dp(65),dp(24),Color.WHITE,true);for(int i=0;i<pages;i++){int col=i%3,row=i/3;RectF r=new RectF(dp(18)+col*(W-dp(24))/3,dp(100)+row*dp(190),dp(10)+(col+1)*(W-dp(24))/3,dp(260)+row*dp(190));paint.setColor(i==page?0xff7aa530:0xff263640);c.drawRoundRect(r,dp(8),dp(8),paint);text(c,String.valueOf(i+1),r.centerX(),r.centerY()+dp(8),dp(28),Color.WHITE,true);}}
 private void drawEdit(Canvas c,float W,float H){paint.setColor(0xdd111111);c.drawRoundRect(new RectF(dp(12),H-dp(205),W-dp(12),H-dp(120)),dp(14),dp(14),paint);text(c,"Widgets",W*.2f,H-dp(155),dp(16),Color.WHITE,true);text(c,"Overview",W*.5f,H-dp(155),dp(16),Color.WHITE,true);text(c,"Settings",W*.8f,H-dp(155),dp(16),Color.WHITE,true);}
 @Override public boolean onTouchEvent(android.view.MotionEvent e){gestures.onTouchEvent(e);if(drawer||overview)return true;if(e.getAction()==MotionEvent.ACTION_MOVE){drag=e.getX()-downX;invalidate();}else if(e.getAction()==MotionEvent.ACTION_UP&&Math.abs(drag)>2)finishDrag(0);return true;}
 private void finishDrag(float velocity){float chosen=0;if(Math.abs(drag)>getWidth()*.18f||Math.abs(velocity)>900){int dir=drag<0?1:-1;page=(page+dir+pages)%pages;chosen=drag<0?-getWidth():getWidth();}final float from=drag,target=chosen;settle=ValueAnimator.ofFloat(0,1);settle.setDuration(400);settle.setInterpolator(ease);settle.addUpdateListener(a->{float v=(float)a.getAnimatedValue();drag=from+(target-from)*v;if(v>.5f&&target!=0)drag-=target;invalidate();});settle.addListener(new AnimatorListenerAdapter(){public void onAnimationEnd(Animator a){drag=0;prefs.edit().putInt("page",page).apply();invalidate();}});settle.start();}
 private boolean tap(float x,float y){float W=getWidth(),H=getHeight();if(drawer){if(y<dp(90)&&x>W-dp(80)){drawer=false;invalidate();return true;}int i=(int)((y-dp(65))/dp(112))*4+(int)(x/(W/4));if(i>=0&&i<apps.size())activity.launch(apps.get(i));return true;}if(overview){int col=(int)(x/(W/3)),row=(int)((y-dp(100))/dp(190)),p=row*3+col;if(p>=0&&p<pages){page=p;overview=false;invalidate();}return true;}if(editing){if(y>H-dp(210)&&y<H-dp(110)){if(x<W/3)activity.chooseWidget();else if(x<W*2/3){overview=true;editing=false;}else settings();invalidate();return true;}editing=false;invalidate();return true;}if(dock.contains(x,y)){if(x>W*.35f&&x<W*.65f){drawer=true;invalidate();}else if(x>W*.66f){editing=true;invalidate();}else {Intent i=new Intent(Intent.ACTION_DIAL);activity.startActivity(i);}return true;}float start=clock.bottom+dp(45),cellW=W/columns,cellH=(H-dp(125)-start)/rows;if(y>start&&y<H-dp(125)){int i=(int)((y-start)/cellH)*columns+(int)(x/cellW)+page*columns*rows;if(i>=0&&i<favorites.size())activity.launch(favorites.get(i));}return true;}
 private void settings(){final String[] opts={"Icon size: 56 dp","Icon size: 64 dp","Grid: 4 columns","Grid: 5 columns","Android Home settings"};new AlertDialog.Builder(activity).setTitle("Rosie settings").setItems(opts,(d,w)->{if(w<2){iconDp=w==0?56:64;prefs.edit().putInt("icons",(int)iconDp).apply();}else if(w<4){columns=w==2?4:5;prefs.edit().putInt("columns",columns).apply();}else activity.startActivity(new Intent(android.provider.Settings.ACTION_HOME_SETTINGS));invalidate();}).show();}
 void addWidget(AppWidgetHostView v,int id){if(widget!=null)removeView(widget);widget=v;addView(v);requestLayout();invalidate();}
 boolean closeLayer(){if(drawer||overview||editing){drawer=overview=editing=false;invalidate();return true;}if(page!=3){page=3;invalidate();return true;}return false;}
 private float dp(float v){return v*density;} private void text(Canvas c,String s,float x,float y,float sz,int color,boolean center){paint.setShader(null);paint.setColor(color);paint.setTextSize(sz);paint.setTypeface(Typeface.create("sans",Typeface.NORMAL));paint.setTextAlign(center?Paint.Align.CENTER:Paint.Align.LEFT);paint.setShadowLayer(dp(2),0,dp(2),Color.BLACK);c.drawText(s,x,y,paint);paint.clearShadowLayer();}
 private static final class PolynomialEase implements TimeInterpolator {public float getInterpolation(float t){return 5.5f*t-13*t*t+16*t*t*t-10*t*t*t*t+2.5f*t*t*t*t*t;}}
}
